# .github/workflows/douban.yml
name: douban
on: 
  workflow_dispatch: 

  schedule:
  - cron: "0 6 * * *"
  watch:
    types: [started]

jobs:
  douban:
    name: Douban mark data sync
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    # 确保在 dev 分支上进行操作
    - name: Set up dev branch
      run: |
        git fetch origin
        git checkout dev || git checkout -b dev

    - name: movie
      uses: lizheming/doumark-action@master
      with:
        id: 237542649
        type: movie
        format: csv
        dir: ./static/douban

    - name: book
      uses: lizheming/doumark-action@master
      with:
        id: 237542649
        type: book
        format: csv
        dir: ./static/douban
  
    - name: Commit
      uses: EndBug/add-and-commit@v9
      with:
        message: 'chore: update douban data'
        add: './static/douban'
        branch: dev
